Repository MadhushaPrasad/Diagon-Alley, pull requests merged in 2022-10, with the labels that each got.

#2 Feat(readme) : add some content to readme file
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#3 Feature/dev
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 Update Readme file
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 How to contribute part is not scrolling in README file
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#20 Create the database #7
  document/sql/Diagon-Alley.sql
  pages/.gitkeep
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#35 Create DB Connection #34
  db/DBConnection.php
Labels: help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#49 added the signup page
  sign-up page/index.html
  sign-up page/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#51 Added navbar
  components/navbar.html
  components/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#63 #signup php file
  index.php
  signup.php
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
