Repository MadhushaPrasad/Diagon-Alley, pull requests merged in 2023-10, with the labels that each got.

#65 Fix : remove wrong things and add .gitignore file
  .gitignore
  .idea/.gitignore
  .idea/Diagon-Alley.iml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
  components/navbar.html
  index.html
  index.php
  pages/home.html
  pages/signup.php
  register1.html
  register2.html
  sign-up page/index.html
  sign-up page/style.css
  signup.php
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#66 Update php.yml
  .github/workflows/php.yml
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, reopen, hacktoberfest2023

#71 Integrate Sonar cube to these repo #69
  .github/workflows/build.yml
  sonar-project.properties
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#75 Update README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#70 Completed signup page
  assets/img/Hide.svg
  assets/img/SignUp.png
  assets/img/facebook-icon.png
  assets/img/google-icon.png
  assets/img/logo.svg
  pages/signup.css
  pages/signup.php
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023
