Repository MadhushaPrasad/Diagon-Alley, pull requests merged in 2024-10, with the labels that each got.

#79 Implement the startup ui
  README.md
  assets/img/Hide.svg
  assets/img/SignUp.png
  assets/img/Vector.png
  assets/img/facebook-icon.png
  assets/img/google-icon.png
  assets/img/logo.svg
  assets/img/young woman imagining things while reading e-book.svg
  components/contactus.css
  components/contactus.php
  components/contri.css
  components/contri.php
  components/letestbook.css
  components/letestbook.php
  components/navbar.css
  components/navbar.php
  components/style.css
  pages/signup.php
  pages/startUp.css
  pages/startUp.php
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#82 Start up page
  assets/img/Vector.png
  assets/img/young woman imagining things while reading e-book.svg
  components/contactus.css
  components/contactus.php
  components/contri.css
  components/contri.php
  components/letestbook.css
  components/letestbook.php
  components/navbar.css
  components/navbar.php
  components/style.css
  pages/signup.css
  pages/signup.php
  pages/startUp.css
  pages/startUp.php
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#87 Revert commit
  .gitignore
  assets/img/Vector.png
  assets/img/young woman imagining things while reading e-book.svg
  pages/startUp.css
  pages/startUp.php
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#81 Implement the navbar component
  components/navbar.css
  components/navbar.php
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#80 Implement the contactuUs component in in home page
  components/contactus.css
  components/contactus.php
  pages/login.css
  pages/login.php
  pages/signup.css
  pages/signup.php
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#102 feat: add responsive footer with logo, links, and contact section
  assets/css/styles.css
  components/contactus.css
  components/contactus.php
  components/style.css
  index.php
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, hactoberfest2024
